databases:
  - name: campus_db
    plan: free
    databaseName: campus_db
    user: root

services:
  - type: web
    plan: free
    name: campus_event
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn campus_event.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: campus_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4